language: java

install:
  - ./install_pmachine.sh
  - mvn package

script:
  - mvn test -B
  - python src/test/python/codegen.py
  - python src/test/python/codegen_fail.py

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7